[platformio]
src_dir = firmware/TeensyMaestro

[env:teensy]
platform = teensy
framework = arduino
board = teensy41

monitor_speed = 115200

build_flags =
  -DUSB_MTPDISK_SERIAL

lib_extra_dirs =
  vendor-libraries

lib_ldf_mode = chain+

lib_deps =
  bxparks/AceTime
  https://github.com/FrankBoesing/T4_PowerButton.git
  adafruit/Adafruit MCP23017 Arduino Library
  LinnesLab/KickSort
