[platformio]
src_dir = firmware/TeensyMaestro

[env:teensy]
platform = teensy
framework = arduino
board = teensy41

; Säg åt PlatformIO att vi använder ett eget verktyg
upload_protocol = custom

; TyCommander-uppladdning
; Vi använder citationstecken runt sökvägen pga mellanslag i "Program Files (x86)"
upload_command = "C:\Program Files (x86)\TyTools\tycmd.exe" upload -B 18009060 --wait $SOURCE

monitor_speed = 115200
build_flags =
  -DUSB_MTPDISK_SERIAL

lib_extra_dirs =
  vendor-libraries

lib_ldf_mode = chain+

lib_deps =
  bxparks/AceTime
  https://github.com/FrankBoesing/T4_PowerButton.git
  adafruit/Adafruit MCP23017 Arduino Library
  LinnesLab/KickSort