[platformio]
src_dir = firmware/TeensyMaestro

[env:teensy]
platform = teensy@5.0.0
framework = arduino
board = teensy41
upload_protocol = custom
upload_command = tycmd upload -B 18009060 --wait $SOURCE
monitor_speed = 115200

; Run the Python script after build to rename firmware
extra_scripts = post:name_firmware.py

build_flags =
  -DUSB_MTPDISK_SERIAL

lib_extra_dirs =
  vendor-libraries

lib_ldf_mode = chain+

lib_deps =
  bxparks/AceTime
  https://github.com/FrankBoesing/T4_PowerButton.git
  adafruit/Adafruit MCP23017 Arduino Library
  LinnesLab/KickSort